services:
  - type: web
    name: seeyuh
    runtime: python
    buildCommand: bash install_ffmpeg.sh && pip install -r requirements.txt
    startCommand: python3 start.py
    healthCheckPath: /status
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.4"