import os, logging, requests, random, time, aiohttp, asyncio, google.generativeai as genai
from datetime import datetime
from bs4 import BeautifulSoup
from typing import List
from dotenv import load_dotenv
from urllib.parse import quote_plus, urlparse

# Load environment variables
load_dotenv()
GOOGLE_API_KEY = os.getenv('GEMINI_API')

# Configure the Google Generative AI SDK
genai.configure(api_key=GOOGLE_API_KEY)

# Configure logging for Unicode
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler("bot.log", encoding='utf-8'),
        logging.StreamHandler()
    ]
)
from engine.ai.gemini_models import (
    pro10creative,
    pro15creative,
    pro15normal,
    flash15normal,
    flash15creative,
    flash158bn,
    flash158bc
)
def extract_current_query(prompt: str) -> str:
    """Extract clean search query from bot prompt format."""
    if "Current query: from user" in prompt:
        # Get text after "Current query: from user" pattern
        query = prompt.split("Current query: from user", 1)[1]
        # Get actual message after last colon
        query = query.split(":")[-1].strip()
        # Remove trailing punctuation and clean whitespace
        query = query.rstrip('.!?')
        query = ' '.join(query.split())
        return query
    return prompt.strip()
    
def needs_realtime_data(query: str) -> bool:
    """Check if query needs real-time data."""
    # Keywords that suggest need for current info
    time_keywords = ['now', 'today', 'current', 'latest', 'recent']
    topic_keywords = ['president', 'weather', 'news', 'price', 'score', 
                     'stock', 'match', 'game', 'election']
    
    query_lower = query.lower()
    # Check for time indicators
    has_time = any(keyword in query_lower for keyword in time_keywords)
    # Check for topics that need current data
    has_topic = any(keyword in query_lower for keyword in topic_keywords)
    
    # Return True if query contains time indicator OR topic needing current data
    return has_time or has_topic

async def get_search_results(query: str, num_results: int = 3) -> str:
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }
    search_url = f"https://www.google.com/search?q={quote_plus(query)}&safe=active"
    
    async with aiohttp.ClientSession() as session:
        async with session.get(search_url, headers=headers) as resp:
            if resp.status == 200:
                html = await resp.text()
                soup = BeautifulSoup(html, 'html.parser')
                
                results = []
                for g in soup.find_all('div', class_='tF2Cxc')[:num_results]:
                    title = g.find('h3').text if g.find('h3') else "No title"
                    link = g.find('a')['href'] if g.find('a') else "No link"
                    description = g.find('div', class_='VwiC3b').text if g.find('div', class_='VwiC3b') else "No description"
                    
                    if title and description:
                        domain = urlparse(link).netloc.replace("www.", "")
                        results.append(f"{title}\n{description[:300]}...\nSource: {domain}\n")
                
                if results:
                    return "\n".join(results)
                    
    return "No results found."

async def get_ai_response(prompt):
    # Extract the current query from the prompt
    current_query = extract_current_query(prompt)
    logging.info(f"Extracted query: {current_query}")
    
    # Check if we need real-time data
    if needs_realtime_data(current_query):
        logging.info("Real-time data needed, fetching search results")
        search_results = await get_search_results(current_query)  # Added await here
        if search_results:
            prompt = (
                f"Google search results based on {current_query}:\n\n"
                f"{search_results}\n\n"
                f"{prompt}"
            )
        
    if "NOTE - Image automatically generated by stable diffusion for:" in prompt:
        systemInstruction = f"You are a discord bot named seeyuh. arkodeep is your developer, your responses are chill asf and very informal gen-z style. You are an automoderation, entertainment, music and games bot but also designed to help users with their queries. You will generate responses using AI and remember images will be generated using stable diffusion automatically when user prompts it, so you need not worry. You can provide information about the bot, list available commands, respond to user queries and access latest data from internet. You can use the `/help` command to see available commands."
    else:
        systemInstruction = f"You are a discord bot named seeyuh. arkodeep is your developer, your responses are chill asf and very informal gen-z style. You are an automoderation, entertainment, music and games bot but also designed to help users with their queries. You will generate responses using AI and try using same languge as the query. You can provide information about the bot, list available commands, respond to user queries and access latest data from internet. You can use the `/help` command to see available commands."
    current_datetime = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    query = f"\n{systemInstruction} Today's date and time is {current_datetime}", f"\n{prompt}"
    logging.info(f"Query to AI: {query}")
    model = flash15normal
    try:
        response = model.generate_content(query)
        return response.text or "I'm not sure how to respond to that."
        logging.info(f"AI response: {response.text}")
    except Exception as e:
        print(f"Error generating response: {e}")
        return "Sorry, I could not process that."

# Function to get AI response
async def slash_ai_response(prompt):
    systemInstruction = f"You are a discord bot named seeyuh. Your responses are chill asf and very informal gen-z style. You will do exactly what the user asks you to do."
    query = f"\n{systemInstruction}", f"\n{prompt}"
    model = flash15creative
    try:
        response = model.generate_content(query)
        return response.text or "I'm not sure how to respond to that."
    except Exception as e:
        print(f"Error generating response: {e}")
        return "Sorry, I could not process that."
    
async def slash_ai8b_response(prompt):
    systemInstruction = f"You are a discord bot named seeyuh. Your responses are chill asf and very informal gen-z style. You will do exactly what the user asks you to do."
    query = f"\n{systemInstruction}", f"\n{prompt}"
    model = flash158bc
    try:
        response = model.generate_content(query)
        return response.text or "I'm not sure how to respond to that."
    except Exception as e:
        print(f"Error generating response: {e}")
        return "Sorry, I could not process that."
    
async def code_ai_response(prompt, language=None, framework=None):
    systemInstruction = f"You are a discord bot named seeyuh. Your responses are chill asf and very informal gen-z style. You will strictly only generate code and answer programming related questions along with code snippets."
    language_info = f" in {language}" if language else ""
    framework_info = f" using {framework}" if framework else ""
    query = f"\n{systemInstruction}", f"User is asking for AI generated code{language_info}{framework_info} for prompt: {prompt}"
    model = pro15normal
    try:
        response = model.generate_content(query)
        return response.text or "I'm not sure how to respond to that."
    except Exception as e:
        print(f"Error generating response: {e}")
        return "Sorry, I could not process that."
    
async def explain_ai_response(prompt):
    systemInstruction = f"You are a discord bot named seeyuh. You will roleplay as professor seeyuh. You will strictly only explain serious concepts or topics in details covering the most important key information. Your message should be well structured to be displayed in discord and should not be too long."
    query = f"\n{systemInstruction}", f"\n User is asking a detailed explaination for: {prompt}"
    model = pro15creative
    try:
        response = model.generate_content(query)
        return response.text or "I'm not sure how to respond to that."
    except Exception as e:
        print(f"Error generating response: {e}")
        return "Sorry, I could not process that."
    
async def ask_ai_response(prompt):
    systemInstruction = f"You are a discord bot named seeyuh. Your responses are brief and concise. You will strictly only answer questions in a straightforward and simple manner keeping responses as short as possible."
    query = f"\n{systemInstruction}", f"\n User is asking: {prompt}"
    model = flash158bn
    try:
        response = model.generate_content(query)
        return response.text or "I'm not sure how to respond to that."
    except Exception as e:
        print(f"Error generating response: {e}")
        return "Sorry, I could not process that."
    
async def mystery(prompt):
    systemInstruction = f"You are a discord bot named seeyuh. Your responses are chill asf and very informal gen-z style. You are getting a brainfart."
    query = f"\n{systemInstruction}", f"\n{prompt}"
    model = flash158bc
    try:
        response = model.generate_content(query)
        return response.text or "Nmm sure AI'm nothow spond ato ethat.to respon"
    except Exception as e:
        print(f"Error generating response: {e}")
        return "Sorry."
    
async def translate(prompt):
    systemInstruction = f"You are a discord bot named seeyuh. Your will assume the role of a professional translator. You will strictly only translate text from one language to another."
    query = f"\n{systemInstruction}", f"\n{prompt}"
    model = pro15normal
    try:
        response = model.generate_content(query)
        return response.text or "I'm not sure how to respond to that."
    except Exception as e:
        print(f"Error generating response: {e}")
        return "Sorry, I could not process that."
    
async def prompt_ai_response(prompt, model):
    systemInstruction = f"You are a discord bot named seeyuh. Prompt:"
    query = f"\n{systemInstruction}", f"\n{prompt}"
    try:
        response = model.generate_content(query)
        return response.text or "I'm not sure how to respond to that."
    except Exception as e:
        print(f"Error generating response: {e}")
        return "Sorry, I could not process that."